name: Deploy Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami

            echo "HOME=$HOME"

            ls -la ~/.ssh || true
            ls -la ~/.ssh/hasna || true

            echo "===== SSH TEST ====="
            ssh -vT git@github.com || true

            echo "===== GIT SSH COMMAND ====="
            export GIT_SSH_COMMAND="ssh -i /home/ubuntu/.ssh/hasna/id_ed25519 -o StrictHostKeyChecking=no"

            echo "$GIT_SSH_COMMAND"

            cd ~/hasna/next_todolist

            git remote -v

            git pull origin main || true