name: Deploy Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            # Point to the updated ed25519 key path
            export GIT_SSH_COMMAND="ssh -i /home/ubuntu/.ssh/hasna/id_ed25519 -o StrictHostKeyChecking=no"
            
            cd /home/ubuntu/hasna/next_todolist
            git pull origin main
            
            npm install
            npm run build
            pm2 restart next-todolist
            pm2 save